coverage:
  status:
    project:
      default:
        # requires at least the same code coverage as base
        target: auto
        # allows a drop of the code coverage in relation to the base of `threshold`
        threshold: 5%
