name: Build with Maven and Release

on:
  push:
    branches: [master, beta]
  pull_request:
    branches: [master, beta, develop, next]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  
    - name: Build with Maven
      run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
    - uses: codecov/codecov-action@v2

  semantic-release:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta' }}
    name: Create a semantic release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Install semantic-release globally
        run: sudo npm install --prefer-offline --no-audit --global semantic-release@^17.4.4 @semantic-release/exec@^5.0.0 @semantic-release/git@^9.0.0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.BUMP_GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.BUMP_GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.BUMP_GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.BUMP_GIT_EMAIL }}
        run: semantic-release
